---
- name: Installer et démarrer un serveur web Nginx
  hosts: targets
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: S'assurer que le service Nginx est démarré et activé au démarrage
      service:
        name: nginx
        state: started
        enabled: yes
